var familyInUkDetailsListCommands = {
  submit: function() {
    this.api.pause(1000);
    return this.waitForElementVisible('@body', 1000)
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION ONE')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION THREE')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@no')
			.click('@saveAndContinue')
  },
  submitThirty: function() {
    this.api.pause(1000);
    return this.waitForElementVisible('@body', 1000)
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION ONE')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.setValue('@relationship', 'Cousin')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'RELATION TWO')
			.setValue('@nationality', 'British Citizen')
			.click('@body')
			.click('@saveAndContinue')
			.click('@yes')
  }
};

module.exports = {
  commands: [familyInUkDetailsListCommands],
	elements: {
		body: 'body',
		relationship: {
			selector: 'input[id=relationship]'
		},
		givenName: {
			selector: 'input[id=givenName]'
		},
		familyName: {
			selector: 'input[id=familyName]'
		},
		nationality: {
			selector: 'input[id=nationalityRef_ui]'
		},
		yes: {
			selector: 'input[id=addAnother_true]'
		},
		no: {
			selector: 'input[id=addAnother_false]'
		},
    saveAndContinue: {
        selector: 'input[id=submit]'
    },
	},
};