var otherAccommodationDetailsListCommands = {
  submit: function() {
    this.api.pause(1000);
    return this.waitForElementVisible('@body', 1000)
      .setValue('@name', 'PLACE ONE')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE THREE')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@no')
      .click('@saveAndContinue')
  },
  submitMultiple: function() {
    this.api.pause(1000);
    return this.waitForElementVisible('@body', 1000)
      .setValue('@name', 'PLACE ONE')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE THREE')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
      .click('@saveAndContinue')
      .click('@yes')
      .click('@saveAndContinue')
      .setValue('@name', 'PLACE TWO')
      .setValue('@addressLine1', 'Test Line 1')
      .setValue('@addressTownCity', 'Test Town')
      .setValue('@addressPostCode', 'SW1P 4DF')
      .setValue('@fromDay', '16')
      .setValue('@fromMonth', '08')
      .setValue('@fromYear', '2016')
      .setValue('@toDay', '17')
      .setValue('@toMonth', '10')
      .setValue('@toYear', '2016')
  },
};

module.exports = {
  commands: [otherAccommodationDetailsListCommands],
	elements: {
		body: 'body',
		name: {
			selector: 'input[id=name]'
		},
    addressLine1: {
      selector: 'input[id=accommodationDetails_address_line1]'
    },
    addressTownCity: {
      selector: 'input[id=accommodationDetails_address_townCity]'
    },
    addressPostCode: {
      selector: 'input[id=accommodationDetails_address_postCode]'
    },
    fromDay: {
      selector: 'input[id=accommodationDetails_dateRange_from_day]'
    },
    fromMonth: {
      selector: 'input[id=accommodationDetails_dateRange_from_month]'
    },
    fromYear: {
      selector: 'input[id=accommodationDetails_dateRange_from_year]'
    },
    toDay: {
      selector: 'input[id=accommodationDetails_dateRange_to_day]'
    },
    toMonth: {
      selector: 'input[id=accommodationDetails_dateRange_to_month]'
    },
    toYear: {
      selector: 'input[id=accommodationDetails_dateRange_to_year]'
    },
    yes: {
      selector: 'input[id=addAnother_true]'
    },
    no: {
      selector: 'input[id=addAnother_false]'
    },
    saveAndContinue: {
        selector: 'input[id=submit]'
    },
	},
};