var payingForYourVisitDetailsListCommands = {
  submit: function() {
    this.api.pause(1000);
    return this.waitForElementVisible('@body', 1000)
			.click('@someoneIKnow')
			.setValue('@name', 'TEST CONTRIBUTOR ONE')
			.setValue('@addressLine1', 'Test Line 1')
			.setValue('@addressTownCity', 'Test Town')
			.setValue('@addressCountry', 'United Kingdom of Great Britain and Northern Ireland')
			.click('@currency')
			.click('@GBP')
			.setValue('@amount', '1000')
			.setValue('@reason', "Because I'm special")
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.waitForElementVisible('@body', 1000)
			.click('@someoneIKnow')
			.setValue('@name', 'TEST CONTRIBUTOR TWO')
			.setValue('@addressLine1', 'Test Line 1')
			.setValue('@addressTownCity', 'Test Town')
			.setValue('@addressCountry', 'United Kingdom of Great Britain and Northern Ireland')
			.click('@currency')
			.click('@GBP')
			.setValue('@amount', '1000')
			.setValue('@reason', "Because I'm special")
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.waitForElementVisible('@body', 1000)
			.click('@someoneIKnow')
			.setValue('@name', 'TEST CONTRIBUTOR THREE')
			.setValue('@addressLine1', 'Test Line 1')
			.setValue('@addressTownCity', 'Test Town')
			.setValue('@addressCountry', 'United Kingdom of Great Britain and Northern Ireland')
			.click('@currency')
			.click('@GBP')
			.setValue('@amount', '1000')
			.setValue('@reason', "Because I'm special")
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.waitForElementVisible('@body', 1000)
			.click('@someoneIKnow')
			.setValue('@name', 'TEST CONTRIBUTOR THREE')
			.setValue('@addressLine1', 'Test Line 1')
			.setValue('@addressTownCity', 'Test Town')
			.setValue('@addressCountry', 'United Kingdom of Great Britain and Northern Ireland')
			.click('@currency')
			.click('@GBP')
			.setValue('@amount', '1000')
			.setValue('@reason', "Because I'm special")
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.waitForElementVisible('@body', 1000)
			.click('@someoneIKnow')
			.setValue('@name', 'TEST CONTRIBUTOR THREE')
			.setValue('@addressLine1', 'Test Line 1')
			.setValue('@addressTownCity', 'Test Town')
			.setValue('@addressCountry', 'United Kingdom of Great Britain and Northern Ireland')
			.click('@currency')
			.click('@GBP')
			.setValue('@amount', '1000')
			.setValue('@reason', "Because I'm special")
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.waitForElementVisible('@body', 1000)
			.click('@someoneIKnow')
			.setValue('@name', 'TEST CONTRIBUTOR THREE')
			.setValue('@addressLine1', 'Test Line 1')
			.setValue('@addressTownCity', 'Test Town')
			.setValue('@addressCountry', 'United Kingdom of Great Britain and Northern Ireland')
			.click('@currency')
			.click('@GBP')
			.setValue('@amount', '1000')
			.setValue('@reason', "Because I'm special")
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.waitForElementVisible('@body', 1000)
			.click('@someoneIKnow')
			.setValue('@name', 'TEST CONTRIBUTOR THREE')
			.setValue('@addressLine1', 'Test Line 1')
			.setValue('@addressTownCity', 'Test Town')
			.setValue('@addressCountry', 'United Kingdom of Great Britain and Northern Ireland')
			.click('@currency')
			.click('@GBP')
			.setValue('@amount', '1000')
			.setValue('@reason', "Because I'm special")
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.waitForElementVisible('@body', 1000)
			.click('@someoneIKnow')
			.setValue('@name', 'TEST CONTRIBUTOR THREE')
			.setValue('@addressLine1', 'Test Line 1')
			.setValue('@addressTownCity', 'Test Town')
			.setValue('@addressCountry', 'United Kingdom of Great Britain and Northern Ireland')
			.click('@currency')
			.click('@GBP')
			.setValue('@amount', '1000')
			.setValue('@reason', "Because I'm special")
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.waitForElementVisible('@body', 1000)
			.click('@someoneIKnow')
			.setValue('@name', 'TEST CONTRIBUTOR THREE')
			.setValue('@addressLine1', 'Test Line 1')
			.setValue('@addressTownCity', 'Test Town')
			.setValue('@addressCountry', 'United Kingdom of Great Britain and Northern Ireland')
			.click('@currency')
			.click('@GBP')
			.setValue('@amount', '1000')
			.setValue('@reason', "Because I'm special")
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.waitForElementVisible('@body', 1000)
			.click('@someoneIKnow')
			.setValue('@name', 'TEST CONTRIBUTOR THREE')
			.setValue('@addressLine1', 'Test Line 1')
			.setValue('@addressTownCity', 'Test Town')
			.setValue('@addressCountry', 'United Kingdom of Great Britain and Northern Ireland')
			.click('@currency')
			.click('@GBP')
			.setValue('@amount', '1000')
			.setValue('@reason', "Because I'm special")
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.waitForElementVisible('@body', 1000)
			.click('@someoneIKnow')
			.setValue('@name', 'TEST CONTRIBUTOR THREE')
			.setValue('@addressLine1', 'Test Line 1')
			.setValue('@addressTownCity', 'Test Town')
			.setValue('@addressCountry', 'United Kingdom of Great Britain and Northern Ireland')
			.click('@currency')
			.click('@GBP')
			.setValue('@amount', '1000')
			.setValue('@reason', "Because I'm special")
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.waitForElementVisible('@body', 1000)
			.click('@someoneIKnow')
			.setValue('@name', 'TEST CONTRIBUTOR THREE')
			.setValue('@addressLine1', 'Test Line 1')
			.setValue('@addressTownCity', 'Test Town')
			.setValue('@addressCountry', 'United Kingdom of Great Britain and Northern Ireland')
			.click('@currency')
			.click('@GBP')
			.setValue('@amount', '1000')
			.setValue('@reason', "Because I'm special")
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.waitForElementVisible('@body', 1000)
			.click('@someoneIKnow')
			.setValue('@name', 'TEST CONTRIBUTOR THREE')
			.setValue('@addressLine1', 'Test Line 1')
			.setValue('@addressTownCity', 'Test Town')
			.setValue('@addressCountry', 'United Kingdom of Great Britain and Northern Ireland')
			.click('@currency')
			.click('@GBP')
			.setValue('@amount', '1000')
			.setValue('@reason', "Because I'm special")
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.waitForElementVisible('@body', 1000)
			.click('@someoneIKnow')
			.setValue('@name', 'TEST CONTRIBUTOR THREE')
			.setValue('@addressLine1', 'Test Line 1')
			.setValue('@addressTownCity', 'Test Town')
			.setValue('@addressCountry', 'United Kingdom of Great Britain and Northern Ireland')
			.click('@currency')
			.click('@GBP')
			.setValue('@amount', '1000')
			.setValue('@reason', "Because I'm special")
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.waitForElementVisible('@body', 1000)
			.click('@someoneIKnow')
			.setValue('@name', 'TEST CONTRIBUTOR THREE')
			.setValue('@addressLine1', 'Test Line 1')
			.setValue('@addressTownCity', 'Test Town')
			.setValue('@addressCountry', 'United Kingdom of Great Britain and Northern Ireland')
			.click('@currency')
			.click('@GBP')
			.setValue('@amount', '1000')
			.setValue('@reason', "Because I'm special")
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.waitForElementVisible('@body', 1000)
			.click('@someoneIKnow')
			.setValue('@name', 'TEST CONTRIBUTOR THREE')
			.setValue('@addressLine1', 'Test Line 1')
			.setValue('@addressTownCity', 'Test Town')
			.setValue('@addressCountry', 'United Kingdom of Great Britain and Northern Ireland')
			.click('@currency')
			.click('@GBP')
			.setValue('@amount', '1000')
			.setValue('@reason', "Because I'm special")
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.waitForElementVisible('@body', 1000)
			.click('@someoneIKnow')
			.setValue('@name', 'TEST CONTRIBUTOR THREE')
			.setValue('@addressLine1', 'Test Line 1')
			.setValue('@addressTownCity', 'Test Town')
			.setValue('@addressCountry', 'United Kingdom of Great Britain and Northern Ireland')
			.click('@currency')
			.click('@GBP')
			.setValue('@amount', '1000')
			.setValue('@reason', "Because I'm special")
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.waitForElementVisible('@body', 1000)
			.click('@someoneIKnow')
			.setValue('@name', 'TEST CONTRIBUTOR THREE')
			.setValue('@addressLine1', 'Test Line 1')
			.setValue('@addressTownCity', 'Test Town')
			.setValue('@addressCountry', 'United Kingdom of Great Britain and Northern Ireland')
			.click('@currency')
			.click('@GBP')
			.setValue('@amount', '1000')
			.setValue('@reason', "Because I'm special")
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.waitForElementVisible('@body', 1000)
			.click('@someoneIKnow')
			.setValue('@name', 'TEST CONTRIBUTOR THREE')
			.setValue('@addressLine1', 'Test Line 1')
			.setValue('@addressTownCity', 'Test Town')
			.setValue('@addressCountry', 'United Kingdom of Great Britain and Northern Ireland')
			.click('@currency')
			.click('@GBP')
			.setValue('@amount', '1000')
			.setValue('@reason', "Because I'm special")
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.waitForElementVisible('@body', 1000)
			.click('@someoneIKnow')
			.setValue('@name', 'TEST CONTRIBUTOR THREE')
			.setValue('@addressLine1', 'Test Line 1')
			.setValue('@addressTownCity', 'Test Town')
			.setValue('@addressCountry', 'United Kingdom of Great Britain and Northern Ireland')
			.click('@currency')
			.click('@GBP')
			.setValue('@amount', '1000')
			.setValue('@reason', "Because I'm special")
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.waitForElementVisible('@body', 1000)
			.click('@someoneIKnow')
			.setValue('@name', 'TEST CONTRIBUTOR THREE')
			.setValue('@addressLine1', 'Test Line 1')
			.setValue('@addressTownCity', 'Test Town')
			.setValue('@addressCountry', 'United Kingdom of Great Britain and Northern Ireland')
			.click('@currency')
			.click('@GBP')
			.setValue('@amount', '1000')
			.setValue('@reason', "Because I'm special")
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.waitForElementVisible('@body', 1000)
			.click('@someoneIKnow')
			.setValue('@name', 'TEST CONTRIBUTOR THREE')
			.setValue('@addressLine1', 'Test Line 1')
			.setValue('@addressTownCity', 'Test Town')
			.setValue('@addressCountry', 'United Kingdom of Great Britain and Northern Ireland')
			.click('@currency')
			.click('@GBP')
			.setValue('@amount', '1000')
			.setValue('@reason', "Because I'm special")
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.waitForElementVisible('@body', 1000)
			.click('@someoneIKnow')
			.setValue('@name', 'TEST CONTRIBUTOR THREE')
			.setValue('@addressLine1', 'Test Line 1')
			.setValue('@addressTownCity', 'Test Town')
			.setValue('@addressCountry', 'United Kingdom of Great Britain and Northern Ireland')
			.click('@currency')
			.click('@GBP')
			.setValue('@amount', '1000')
			.setValue('@reason', "Because I'm special")
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.waitForElementVisible('@body', 1000)
			.click('@someoneIKnow')
			.setValue('@name', 'TEST CONTRIBUTOR THREE')
			.setValue('@addressLine1', 'Test Line 1')
			.setValue('@addressTownCity', 'Test Town')
			.setValue('@addressCountry', 'United Kingdom of Great Britain and Northern Ireland')
			.click('@currency')
			.click('@GBP')
			.setValue('@amount', '1000')
			.setValue('@reason', "Because I'm special")
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.waitForElementVisible('@body', 1000)
			.click('@someoneIKnow')
			.setValue('@name', 'TEST CONTRIBUTOR THREE')
			.setValue('@addressLine1', 'Test Line 1')
			.setValue('@addressTownCity', 'Test Town')
			.setValue('@addressCountry', 'United Kingdom of Great Britain and Northern Ireland')
			.click('@currency')
			.click('@GBP')
			.setValue('@amount', '1000')
			.setValue('@reason', "Because I'm special")
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.waitForElementVisible('@body', 1000)
			.click('@someoneIKnow')
			.setValue('@name', 'TEST CONTRIBUTOR THREE')
			.setValue('@addressLine1', 'Test Line 1')
			.setValue('@addressTownCity', 'Test Town')
			.setValue('@addressCountry', 'United Kingdom of Great Britain and Northern Ireland')
			.click('@currency')
			.click('@GBP')
			.setValue('@amount', '1000')
			.setValue('@reason', "Because I'm special")
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.waitForElementVisible('@body', 1000)
			.click('@someoneIKnow')
			.setValue('@name', 'TEST CONTRIBUTOR THREE')
			.setValue('@addressLine1', 'Test Line 1')
			.setValue('@addressTownCity', 'Test Town')
			.setValue('@addressCountry', 'United Kingdom of Great Britain and Northern Ireland')
			.click('@currency')
			.click('@GBP')
			.setValue('@amount', '1000')
			.setValue('@reason', "Because I'm special")
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.waitForElementVisible('@body', 1000)
			.click('@someoneIKnow')
			.setValue('@name', 'TEST CONTRIBUTOR THREE')
			.setValue('@addressLine1', 'Test Line 1')
			.setValue('@addressTownCity', 'Test Town')
			.setValue('@addressCountry', 'United Kingdom of Great Britain and Northern Ireland')
			.click('@currency')
			.click('@GBP')
			.setValue('@amount', '1000')
			.setValue('@reason', "Because I'm special")
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.waitForElementVisible('@body', 1000)
			.click('@someoneIKnow')
			.setValue('@name', 'TEST CONTRIBUTOR THREE')
			.setValue('@addressLine1', 'Test Line 1')
			.setValue('@addressTownCity', 'Test Town')
			.setValue('@addressCountry', 'United Kingdom of Great Britain and Northern Ireland')
			.click('@currency')
			.click('@GBP')
			.setValue('@amount', '1000')
			.setValue('@reason', "Because I'm special")
			.click('@saveAndContinue')
			.click('@yes')
			.click('@saveAndContinue')
			.waitForElementVisible('@body', 1000)
			.click('@someoneIKnow')
			.setValue('@name', 'TEST CONTRIBUTOR THREE')
			.setValue('@addressLine1', 'Test Line 1')
			.setValue('@addressTownCity', 'Test Town')
			.setValue('@addressCountry', 'United Kingdom of Great Britain and Northern Ireland')
			.click('@currency')
			.click('@GBP')
			.setValue('@amount', '1000')
			.setValue('@reason', "Because I'm special")
			.click('@saveAndContinue')
  }
};

module.exports = {
  commands: [payingForYourVisitDetailsListCommands],
	elements: {
		body: 'body',
		someoneIKnow: {
			selector: 'input[id=whoIsPayingRef_someoneIKnow]'
		},
		name: {
			selector: 'input[id=payeeName]'
		},
		addressLine1: {
			selector: 'input[id=address_line1]'
		},
		addressTownCity: {
			selector: 'input[id=address_townCity]'
		},
		addressCountry: {
			selector: 'input[id=address_countryRef_ui]'
		},
		currency: {
			selector: 'select[id=amount_currencyRef]'
		},
		GBP: {
			selector: 'option[value=GBP]'
		},
		amount: {
			selector: 'input[id=amount_amount]'
		},
		reason: '#reason',
    saveAndContinue: {
        selector: 'input[id=submit]'
    },
		yes: {
			selector: 'input[id=addAnother_true]'
		},
		no: {
			selector: 'input[id=addAnother_false]'
		},
	},
};