var identityNameListCommands = {
  submitPSAB: function() {
    this.api.pause(1000);
    return this.waitForElementVisible('@body', 1000)
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST')
			.click('@saveAndContinue');
			// .click('@anotherNameFalse')
			// .click('@saveAndContinue');
  },
  submitMCC: function() {
    this.api.pause(1000);
    return this.waitForElementVisible('@body', 1000)
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST')
			.click('@saveAndContinue')
			.click('@anotherNameFalse')
			.click('@saveAndContinue');
  },
  submitTier2: function() {
    this.api.pause(1000);
    return this.waitForElementVisible('@body', 1000)
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST')
			.click('@saveAndContinue')
			.click('@anotherNameFalse')
			.click('@saveAndContinue');
  },
  submitThirtyNames: function() {
    this.api.pause(1000);
    return this.waitForElementVisible('@body', 1000)
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST ONE')
			.click('@saveAndContinue')
			.click('@anotherNameTrue')
			.click('@saveAndContinue')
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST TWO')
			.click('@saveAndContinue')
			.click('@anotherNameTrue')
			.click('@saveAndContinue')
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST THREE')
			.click('@saveAndContinue')
			.click('@anotherNameTrue')
			.click('@saveAndContinue')
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST FOUR')
			.click('@saveAndContinue')
			.click('@anotherNameTrue')
			.click('@saveAndContinue')
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST FIVE')
			.click('@saveAndContinue')
			.click('@anotherNameTrue')
			.click('@saveAndContinue')
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST SIX')
			.click('@saveAndContinue')
			.click('@anotherNameTrue')
			.click('@saveAndContinue')
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST SEVEN')
			.click('@saveAndContinue')
			.click('@anotherNameTrue')
			.click('@saveAndContinue')
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST EIGHT')
			.click('@saveAndContinue')
			.click('@anotherNameTrue')
			.click('@saveAndContinue')
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST NINE')
			.click('@saveAndContinue')
			.click('@anotherNameTrue')
			.click('@saveAndContinue')
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST TEN')
			.click('@saveAndContinue')
			.click('@anotherNameTrue')
			.click('@saveAndContinue')
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST ELEVEN')
			.click('@saveAndContinue')
			.click('@anotherNameTrue')
			.click('@saveAndContinue')
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST TWELVE')
			.click('@saveAndContinue')
			.click('@anotherNameTrue')
			.click('@saveAndContinue')
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST THIRTEEN')
			.click('@saveAndContinue')
			.click('@anotherNameTrue')
			.click('@saveAndContinue')
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST FOURTEEN')
			.click('@saveAndContinue')
			.click('@anotherNameTrue')
			.click('@saveAndContinue')
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST FIFTEEN')
			.click('@saveAndContinue')
			.click('@anotherNameTrue')
			.click('@saveAndContinue')
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST SIXTEEN')
			.click('@saveAndContinue')
			.click('@anotherNameTrue')
			.click('@saveAndContinue')
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST SEVENTEEN')
			.click('@saveAndContinue')
			.click('@anotherNameTrue')
			.click('@saveAndContinue')
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST EIGHTEEN')
			.click('@saveAndContinue')
			.click('@anotherNameTrue')
			.click('@saveAndContinue')
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST NINETEEN')
			.click('@saveAndContinue')
			.click('@anotherNameTrue')
			.click('@saveAndContinue')
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST TWENTY')
			.click('@saveAndContinue')
			.click('@anotherNameTrue')
			.click('@saveAndContinue')
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST TWENTY ONE')
			.click('@saveAndContinue')
			.click('@anotherNameTrue')
			.click('@saveAndContinue')
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST TWENTY TWO')
			.click('@saveAndContinue')
			.click('@anotherNameTrue')
			.click('@saveAndContinue')
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST TWENTY THREE')
			.click('@saveAndContinue')
			.click('@anotherNameTrue')
			.click('@saveAndContinue')
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST TWENTY FOUR')
			.click('@saveAndContinue')
			.click('@anotherNameTrue')
			.click('@saveAndContinue')
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST TWENTY FIVE')
			.click('@saveAndContinue')
			.click('@anotherNameTrue')
			.click('@saveAndContinue')
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST TWENTY SIX')
			.click('@saveAndContinue')
			.click('@anotherNameTrue')
			.click('@saveAndContinue')
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST TWENTY SEVEN')
			.click('@saveAndContinue')
			.click('@anotherNameTrue')
			.click('@saveAndContinue')
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST TWENTY EIGHT')
			.click('@saveAndContinue')
			.click('@anotherNameTrue')
			.click('@saveAndContinue')
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST TWENTY NINE')
			.click('@saveAndContinue')
			.click('@anotherNameTrue')
			.click('@saveAndContinue')
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST THIRTY')
			.click('@saveAndContinue')
			.click('@anotherNameTrue')
			.click('@saveAndContinue')
    	.click('select[id="titleRef"] option[value="Mr"]')
			.setValue('@givenName', 'TEST')
			.setValue('@familyName', 'TEST THIRTY ONE')
			.click('@saveAndContinue')
			.assert.elementNotPresent('@anotherNameTrue');
  }
};

module.exports = {
  commands: [identityNameListCommands],
	elements: {
		body: 'body',
		title: {
			selector: 'select[id=titleRef]'
		},
		givenName: {
			selector: 'input[id=givenName]'
		},
		familyName: {
			selector: 'input[id=familyName]'
		},
		anotherNameTrue: {
			selector: 'input[id=addAnother_true]'
		},
		anotherNameFalse: {
			selector: 'input[id=addAnother_false]'
		},
    saveAndContinue: {
        selector: 'input[id=submit]'
    },
	},
};